apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vhost
data:
  vhost.conf: | 
    #Default settings
    client_max_body_size 64M;
    #fix 504 gateway timeouts, can go in nginx.conf
    fastcgi_connect_timeout       600;
    fastcgi_send_timeout          600;
    fastcgi_read_timeout          600;
    send_timeout                  600;
    #set the location of the cached files, zone, name, size (50 MB) and how long to cache for 30 minutes
    fastcgi_cache_path  /var/run/cache levels=1:2 keys_zone=WORDPRESS-PROXY:10m max_size={{ .Values.nginxSettings.cacheSizeMiB}}m inactive={{ .Values.nginxSettings.cacheInactiveMin }}m use_temp_path=off;
    fastcgi_cache_key $scheme$host$request_uri;
    
    # enables GZIP compression
    gzip on; 
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_vary on;
    gzip_disable "msie6";
    
    # compress outputs labeled with the following file extensions or MIME-types
    # text/html MIME-type is enabled by default and need not be included
    gzip_types
    application/atom+xml
    application/geo+json
    application/javascript
    application/x-javascript
    application/json
    application/ld+json
    application/manifest+json
    application/rdf+xml
    application/rss+xml
    application/vnd.ms-fontobject
    application/wasm
    application/x-web-app-manifest+json
    application/xhtml+xml
    application/xml
    font/eot
    font/otf
    font/ttf
    image/bmp
    image/svg+xml
    text/cache-manifest
    text/calendar
    text/css
    text/javascript
    text/markdown
    text/plain
    text/xml
    text/vcard
    text/vnd.rim.location.xloc
    text/vtt
    text/x-component
    text/x-cross-domain-policy;
    
    gzip_buffers 16 8k;
    
    server {
      listen 8081;
      server_name  _;
      root /var/www/web;
      index index.php;
      # show cache status and any skip cache reason
      add_header WP-Proxy-Cache $upstream_cache_status;
      add_header Cache-BYPASS-Reason $skip_reason;
    
      # define nginx variables
      {{- if .Values.nginxSettings.cacheEnabled }}
      set $do_not_cache 0;
      {{- else }}
      set $do_not_cache 1;
      {{- end }}
      set $skip_reason "";
      set $bypass 0;
    
      # security for bypass so localhost can empty cache
      if ($remote_addr ~ "^(127.0.0.1)$") {
        set $bypass $http_secret_header;
      }
    
      # POST requests and urls with a query string should always go to PHP
      if ($request_method = POST) {
        set $skip_cache 1;
      }
    
      # skip caching WordPress cookies
      if ($http_cookie ~* "comment_author_|wordpress_(?!test_cookie)|wp-postpass_" ) {
        set $do_not_cache 1;
        set $skip_reason "WP Cookie";
      }
    
      # Don't cache URIs containing the following segments
      if ($request_uri ~* "/wp-admin/|/xmlrpc.php|wp-.*.php|/feed/|sitemap(_index)?.xml") {
        set $do_not_cache 1;
        set $skip_reason "WP Uri";
      }
    
      # Don't cache woocommerce pages NL
      if ($request_uri ~* "/winkel/|/winkelmand/|/mijn-account/|/afrekenen/") {
        set $do_not_cache 1;
        set $skip_reason "Woocommerce Uri"; 
      }
    
      # Don't cache woocommerce pages EN
      if ($request_uri ~* "/store/|/cart/|/my-account/|/checkout/|/addons/") {
        set $do_not_cache 1;
        set $skip_reason "Woocommerce Uri"; 
      }
    
      #Don't cache when add-to-cart parameter is set
      if ( $arg_add-to-cart != "" ) { 
      set $do_not_cache 1;
      set $skip_reason "Woocommerce add-to-cart"; 
      }
    
      # Don't cache when woocommerce_items_in_cart cookie is set
      if ( $cookie_woocommerce_items_in_cart ) { 
        set $do_not_cache 1;
        set $skip_reason Woocommerce-cart-items; 
      }
    
      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }
    
      location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|pdf|html|swf)$ {
       expires 30d;
       add_header Cache-Control "public, no-transform";
      }

      # Prevent direct execution of php scripts in app directory
      location /app/ {
        location ~ \.php$ {
          deny all;
        }
      }
    
      location ~ \.php$ {
        fastcgi_no_cache $do_not_cache;
        fastcgi_cache WORDPRESS-PROXY;
        fastcgi_cache_revalidate on; 
        fastcgi_ignore_headers  Expires Cache-Control;
        fastcgi_cache_bypass $bypass $do_not_cache;
        fastcgi_cache_valid 200 301 302 15m;
        fastcgi_cache_valid 404 1m; 
    
        fastcgi_pass unix:/var/run/sockets/php-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param   SCRIPT_FILENAME  /var/www/web$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    
        try_files $uri =404;
      }
    }
