{{- if .Values.persistence.enabled }}
{{- $fullName := include "bedrock-k8s.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $fullName }}-pvc"
  labels:
    {{- include "bedrock-k8s.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
