apiVersion: v1
kind: Service
metadata:
  name: {{ include "bedrock-k8s.fullname" . }}
  labels:
    {{- include "bedrock-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: bedrock-nginx
  selector:
    {{- include "bedrock-k8s.selectorLabels" . | nindent 4 }}
