apiVersion: v2
name: wp-bedrock
description: A Helm chart for Bedrock, a Wordpress boilerplate
type: application
version: 0.1.1
appVersion: "0.1.0"
sources:
  - https://github.com/sebastiaankok/helm-charts
  - https://gitlab.com/sebastiaankok/wp-bedrock-example
  - https://roots.io/bedrock/
maintainers:
- name: Sebastiaan Kok
  email: helm@sebastiaankok.nl
dependencies:
- name: mariadb
  version: "~9.3.11"
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
