apiVersion: v2
name: wp-bedrock
description: A Helm chart for Bedrock, a Wordpress boilerplate
type: application
version: 0.1.4
appVersion: "0.1.0"
sources:
  - https://github.com/sebastiaankok/helm-charts
  - https://gitlab.com/sebastiaankok/wp-bedrock-example
  - https://roots.io/bedrock/
maintainers:
- name: sebastiaankok
  email: sebastiaan@linux.com
dependencies:
- name: mariadb
  version: "~11.1.0"
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
